### ISSUE TITLE
SimpleDivision does not divides

### ISSUE THREAD

**Issue by LuizZak** [AFoundationForSimpleEnterpriseSoftware/SimpleJavaEasyMath#1]
There seems to be an issue involving the SimpleDivision operation where it does not, in fact, divides.

I've included attached to this message sample codes that reproduce the problem.

```
// Creates one SimpleInteger with value 6
SimpleNumber sn_integerValue6 = new SimpleInteger(6);
// Creates one SimpleInteger with value 3
SimpleNumber sn_integerValue3 = new SimpleInteger(3);

// Populate a number collection with the SimpleNumber with value 6 and SimpleNumber with value 3
SimpleNumberCollection snc_coll = new SimpleNumberCollection();
// Add the SimpleInteger with value 6
snc_coll.add(sn_integerValue6);
// Add the SimpleInteger with value 3
snc_coll.add(sn_integerValue3);

// Create the division operation
SimpleOperator so_divider = new SimpleDivision();
// Create a result object, to hold the result of the operation
SimpleResult sr_result = so_divider.calculate(snc_coll);
// Get the result of the operation
SimpleNumber sn_resultNum = sr_result.getNumber();

// Print 2
System.out.println(sn_resultNum.getIntegerValue(true));
```

Running this snippet, you will notice the result is not 2, as expected, but in fact 3 (!).

I've managed to track down the issue using a Java debugger, which resides on sesf/simplejavaeasymath/SimpleDivider.java file line 56:

```
current -= currentNumber.getDoubleValue();
```

You notice how the primitive operator '-=' is in place of the expected '/=' operator.

This issue might have went unnoticed for this long due to the test case only covering the operation performed on 4 and 2, which result on the same number both when divided and subtracted (2).

**Comment by an-empty-string** [comment]
@tcyrus, this is the incorrect solution to the problem. Please rewrite the SimpleDivision operator to actually use the SimpleSubtraction operator, as this is the mathematically correct approach.

**Comment by an-empty-string** [comment]
Works well enough for now.
